### ISSUE TITLE
BUG: CSV file is overwritten without prompt on subsequent scans

### ISSUE THREAD

**Issue by RandomRhythm** [AdamWhiteHat/Judge-Jury-and-Executable#15]
**Description**
CSV file is overwritten without prompt on subsequent scans.

**Error/Exception Message**
Was an exception thrown? No

**Expected Behavior**
Prompt for file replacement when the scan button is hit.

**Actual Behavior**
Prompt for file replacement occurs on text change for output path and not when scan button is hit.

**Steps To Reproduce**
Configure a scan with CSV file output
Begin scan to create CSV output file
Wait for scan to finish or CSV to be created before stopping the scan
Reconfigure for subsequent scan (changing scan path or filters)
Hit scan button
CSV file is replaced without notification

**Comment by AdamWhiteHat** [comment]
This is for the GUI, I presume?

How should the console version handle this? Fail? Overwrite? Prompting would probably break expectations of being able to script/automate this by halting and prompting for input.

Actually I have an idea: If the file exists, change the output filename from {filename}.{ext} to {filename}\_###.{ext} where ### is a counter starting with 001. Basically:
while( {filename}\_{counter}.{ext} exists )
{
     counter++;
}

That's probably what Ill do for the console application unless I hear otherwise from you.

**Comment by RandomRhythm** [comment]
Correct, GUI.

I think the console version should have an argument to overwrite so as to provide that option. Without confirmation via the argument, I feel the default behavior you described is an appropriate way to handle it.

**Comment by AdamWhiteHat** [comment]
Whoops! I thought I closed this.

See these commits for the relevant code change(s):
 - Change to the GUI: [commit ffb5c5efad901dad6d63ba73745e2a0c5fa7955d](https://github.com/AdamWhiteHat/Judge-Jury-and-Executable/commit/ffb5c5efad901dad6d63ba73745e2a0c5fa7955d)
 - Change to the console: [commit 7ef7803e85782197c37b61598259417c1722410d](https://github.com/AdamWhiteHat/Judge-Jury-and-Executable/commit/7ef7803e85782197c37b61598259417c1722410d)
